algoritmo "Cadastro"
var
nome, cidade, email: caractere
idade, resultado: inteiro


inicio
    escreval("Digite seu nome: ")
    leia(nome)
    escreval("Digite sua idade: ")
    leia(idade)
    escreval("Digite seu e-mail: ")
    leia(email)
    escreval("Digite sua cidade: ")
    leia(cidade)
    escreval("Nome: ",nome)
    escreval("Idade: ",idade)
    escreval("Email: ",email)
    escreval("Cidade: ",cidade)
    
    fimalgoritmo