algoritmo "Faixa Etária"
var
i: inteiro
inicio
    escreval("Qual sua idade: ")
    leia(i)
    se i >= 0 e i <= 12 entao
    escreval("Voce é uma Criança!")
    senao se i >= 13 e  i <= 17 entao
    escreval("Voce é um Adolescente!")
    senao se i >= 18 e i <= 59 entao
    escreval("Voce é um Adulto!")
    senao
    escreval("Voce é um Idoso!")
    fimse
    fimse
    fimse
    fimalgoritmo